### ISSUE TITLE
ITEM - Création - Onglet Texte : cliquer fait apparaître "None"

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#100]
ITEM - Création
- Onglet Texte : Quand on clique simplement dans un des champs de l'onglet Texte, cela fait apparaître automatiquement le mot "None", qui apparaît ensuite en consultation.

**Comment by lluc** [comment]
issue #101

**Comment by mnauge** [comment]
Je viens d'essayer, le problème est toujours là :-\
