### ISSUE TITLE
Tous niveaux - Création MARKDOWN : retirer tous les "none"

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#101]
Tous niveaux - Création MARKDOWN:
Le champ Texte est par défaut rempli par "none" > il faudrait le laisser vide. (de plus, tout ce qui est anglophone est malvenu sur Francoralité...)

- Institution : champs Note
- Fonds : champs Description
- Fonds : champs Commentaires
- Enquête : Description
- Enquête : Précisions sur le lieu
- Enquête : Documentation associée
- Enquête : Commentaire
- Item : Description
- Item : Mélodie (transcription alphabétique)
- Item : Résumé
- Item pavé Texte : Texte + Incipit + Refrain + Ritournelle du conte

**Comment by mnauge** [comment]
Problème résolu lors de la **création d'un nouvel élément**. Pour les éléments déjà créés le problème est toujours visible.

**Comment by mnauge** [comment]
Mais c'est effectivement normal qu'il n'y ai pas d'effet rétroactif là dessus !
