### ISSUE TITLE
[enum] voix/instrument : création impossible

### ISSUE THREAD

**Issue by mnauge** [lluc/telemeta-integration#103]
Lors de la création d'une voix/instrument on a une erreur 502.

**Comment by mnauge** [comment]
Question : 
la création d'une nouvelle entrée de Classification Hornbostel-Sachs se fait dans 
Voix/Instruments - Création quand on crée un nouveau voix instrument, c'est bien ça ?!
Si oui je viens d'essayer d'ajouter une entrée de la forme : 
```
422.212 : 422.2 : saxophone à perce conique
```
Mais l'UI me dit veuillez saisir un code numérique  Hornbostel-Sachs... C'est quoi  la bonne forme numérique pour mon entrée de saxophone ? Merci

**Comment by lluc** [comment]
Forme numérique correcte : **422.412**

**Comment by mnauge** [comment]
Je viens de voir qu'il faut créer avant une  classification Hornbostel-Sachs ... chose que je n'avais pas faite... C'est typiquement une chose qui devrait un jour arriver dans un thésaurus ! Ou au moins créé une bonne fois pour toute. Merci pour l'info.

**Comment by mnauge** [comment]
Ok, ça marche
