### ISSUE TITLE
[item] Pré-saisie des personnes

### ISSUE THREAD

**Issue by lluc** [lluc/telemeta-integration#104]
A la création d'un item, les champs de saisie des personnes ( enquêteurs, informateurs) sont pré-remplis à partir des informations de l'enquête.

**Comment by Alexandre-S1** [comment]
https://docs.google.com/spreadsheets/d/1aVCrrNrTD61xNLFX36lr-L7P_bJwlJ3JbxDPAuw6cmE/edit#gid=1280486778

**Comment by mnauge** [comment]
ok.

**Comment by mnauge** [comment]
vérifié sur UPOI_AFE_0000_0001
