### ISSUE TITLE
Titre (en consultation) : retirer la cote

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#108]
Concernant le titre en haut de page (en police rouge), en consultation d'un.e :
- fonds
- mission
- enquête
- item

Il est indiqué par exemple : 
 Item : UPOI_AFE_0000_0015_001 - La destinée la rose au bois [LAF] 
**-> Retirer la cote pour ne laisser que le titre textuel, afin de gagner en clarté :** 
 Item : La destinée la rose au bois [LAF] 

Attention, au niveau mission, dans le titre on dirait que seule la cote apparaît, et pas le titre.
https://app.preprod.francoralite.net/mission/1

C'est parfait au niveau institution : 
https://app.preprod.francoralite.net/institution/1

**Comment by mnauge** [comment]
c'est bon.
