### ISSUE TITLE
Impossible d'intégrer Média associé dans un Fonds

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#109]
Impossible d'intégrer Média associé dans un Fonds avec un id Nakala. 
Résultat :
_**Web Page Blocked
Access to the web page you were trying to visit has been blocked in accordance with TGIR HUMA-NUM policy
Please contact system administrator if you believe this is in error.
URL: 134.158.38.115/fond/edit/3
Category: hn_url_by_ip**_

Ça fonctionne aux autres niveaux.

**Comment by mnauge** [comment]
Pendant la phase de création de ce fonds https://app.preprod.francoralite.net/fond/10 j'ai pu ajouter mon média associé :-/

**Comment by Alexandre-S1** [comment]
(En revanche, ça ne fonctionne pas en ajout à un fonds existant.)

**Comment by mnauge** [comment]
Non, mais c'est probablement la même erreur que "modification" fonds issue #111

**Comment by Alexandre-S1** [comment]
En effet : je clos l'issue ?
