### ISSUE TITLE
Message d'erreur à l'ajout d'un nouveau fonds

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#110]
Résultat après validation : 

**Web Page Blocked
Access to the web page you were trying to visit has been blocked in accordance with TGIR HUMA-NUM policy

Please contact system administrator if you believe this is in error.

URL: 134.158.38.115/institution/1

Category: hn_url_by_ip**

Cependant le fonds est créé.

**Comment by mnauge** [comment]
Je viens de créer ce matin le fonds suivant :
https://app.preprod.francoralite.net/fond/9

Tu peux refaire une essai ?

**Comment by Alexandre-S1** [comment]
Oui mea culpa, désolé, ça marche, je n'ai plus ce message "Web Page Blocked" qui est lié à un autre navigateur mal configuré.
Je clos l'issue.
