### ISSUE TITLE
Impossible de modifier un fonds

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#111]
Résultat après validation :
**Web Page Blocked
Access to the web page you were trying to visit has been blocked in accordance with TGIR HUMA-NUM policy

Please contact system administrator if you believe this is in error.

URL: 134.158.38.115/fond/edit/1

Category: hn_url_by_ip**

-

Les modifications ne sont pas prises en compte

**Comment by mnauge** [comment]
Moi je viens de modifier le fonds https://app.preprod.francoralite.net/fond/9
ça n'a pas mis de message d'erreur, 
mais ma modif. n'est pas sauvegardé. :-(

**Comment by Alexandre-S1** [comment]
Pareil chez moi avec Firefox.
Ma modif n'est pas sauvegardée et le bouton validation ne renvoie pas vers la page en mode consultation.

Je n'ai plus message "Web Page Blocked" qui est lié à un autre navigateur mal configuré.

**Comment by mnauge** [comment]
ça me rassure, javais peur d'un bug ponctuel difficile à reproduire.
Là au moins nous avons les mêmes soucis ^^.

**Comment by mnauge** [comment]
Luc : Apparemment le problème vient du contrôle de non-redondance de la cote du fonds. Le contrôle de non-redondance ne devrait être fait qu'à la création d'un fond, pas à sa modification.

**Comment by mnauge** [comment]
ça marche !!!!
