### ISSUE TITLE
LIEU > Ajouter > 502 Bad Gateway

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#112]
https://app.preprod.francoralite.net/location_gis/add

**Comment by lluc** [comment]
"Effet de bord" dû à une précedente modification du  TemplateTag *markdown_editor*. [ https://github.com/lluc/telemeta-integration/blob/dca5048117c203f3f47914276cacd5a94576e22f/telemeta_mshs/apps/telemeta_front/templatetags/markdown_extra.py ](Source du commit)
L'appel au TemplateTag est incomplet, ce qui provoque un bug lors de la composition de la page.

**Comment by mnauge** [comment]
ça marche je peux ajouter un nouveau lieux :-)

NB : je ne sais pas comment le supprimer :-(

**Comment by lluc** [comment]
@mnauge La suppression est possible sur la fiche du lieu ( bouton *supprimer*).
