### ISSUE TITLE
ITEM consultation : champ "Contexte d'enregistrement" reste vide

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#118]
Le champ "Contexte d'enregistrement" en consultation d'item reste vide. (Il devrait afficher le résultat du champ correspondant rempli au niveau enquête)

**Comment by mnauge** [comment]
Je ne suis pas sure de bien comprendre. Alexandre peux-tu te charger de faire cette vérification ?

**Comment by Alexandre-S1** [comment]
Oui c'est bon, le champ n'est plus vide.
