### ISSUE TITLE
Possibilité de cotes multiples Coirault/Laforte. 

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#119]
Ceci n'est pas urgent :-)

Serait-il possible d'avoir la possibilité d'ajouter une 2e ou une 3e référence Coirault / Laforte ?
(à l'image des médias associés, avec leur bouton +ajouter)

**Comment by lluc** [comment]
Actuellement, il est possible de saisir plusieurs références _Coirault_ pour un même item.

**Comment by Alexandre-S1** [comment]
Ah en effet, par tokens multiples. Désolé pour l'issue inutile !




Le 2 juil. 2020 à 11:25, lluc <notifications@github.com<mailto:notifications@github.com>> a écrit :



Actuellement, il est possible de saisir plusieurs références Coirault pour un même item.
