### ISSUE TITLE
Changement automatique de Personne

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#122]
L'informateur de cet item : https://app.preprod.francoralite.net/item/10 était "Joseph Larade"

Je modifie la fiche et remplace l'informateur par "Caesar Vincent", je valide, changement bien pris en compte.

Je veux compléter la fiche, je clique sur "éditer" -> l'informateur se rechange automatiquement en "Joseph Larade".

**Comment by lluc** [comment]
@Alexandre-S1 Je n'arrive pas à reproduire le bug sur la machine de développement.  
Mais cela est peut-être dû à la correction d'autre bugs. A re-tester une fois le déploiement effectué.

**Comment by mnauge** [comment]
c'est bon.
