### ISSUE TITLE
ITEM / édition : le champ "informateur" se vide

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#126]
item https://app.preprod.francoralite.net/item/edit/12 > bouton éditer > le champ informateur, qui était rempli, est vidé.

**Comment by mnauge** [comment]
j'ai un 502 Bad Gateway quand je passe en mode édition/modifier un item...
J'ai essayé sur tous les items.
Cependant la consultation fonctionne toujours.

**Comment by mnauge** [comment]
La création fonctionne.

**Comment by lluc** [comment]
@mnauge J'ai corrigé le bug dans le commit https://github.com/lluc/telemeta-integration/commit/90426ea5eeb5543396a26c38c2377ffa6affe832

**Comment by mnauge** [comment]
c'est bon
