### ISSUE TITLE
FONDS et MISSION : liste des LIEUX > mettre à la ligne

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#133]
En consultation, mettre à la ligne chaque LIEU de la liste, car c'est difficile de s'y retrouver lorsqu'il y en a beaucoup
![Sans titre](https://user-images.githubusercontent.com/58727595/87068787-6357f800-c216-11ea-9559-e1f8297ad28d.jpeg)

**Comment by mnauge** [comment]
ok. vérifié en issue #134
