### ISSUE TITLE
FONDS et MISSIONS : lisibilité liste des PERSONNES

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#134]
En consultation, mettre à la ligne chaque PERSONNE de la liste, car c'est difficile de s'y retrouver lorsqu'il y en a beaucoup
![Sans titre](https://user-images.githubusercontent.com/58727595/87068787-6357f800-c216-11ea-9559-e1f8297ad28d.jpeg)

**Comment by mnauge** [comment]
ok, vérification faite : https://app.preprod.francoralite.net/mission/1
![image](https://user-images.githubusercontent.com/30431973/88023456-5b128d80-cb31-11ea-8e9c-e06e27d98ab3.png)

**Comment by mnauge** [comment]
Faut-il faire ma même chose au niveau Enquete ...?!

**Comment by Alexandre-S1** [comment]
Merci d'y penser, oui !
