### ISSUE TITLE
LIEUX > les listes "enquete" et "item" sont vides

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#137]
Sur la fiche d'un LIEU PAR ENQUETE, il manque le rapatriement des listes d'enquêtes et items qui y sont rattachées : 

![Sans titre](https://user-images.githubusercontent.com/58727595/87069660-e037a180-c217-11ea-8127-5fa4e270d14d.jpeg)

**Comment by mnauge** [comment]
ok. vérification sur https://app.preprod.francoralite.net/location_gis/2
