### ISSUE TITLE
ENQUETE > Editer : Message d'erreur pour certaines enquêtes

### ISSUE THREAD

**Issue by Marion-L1** [lluc/telemeta-integration#142]
Un message d'erreur s'inscrit lorsque je tente de modifier la fiche Enquête à partir de laquelle je viens de créer des items. D'autres enquêtes réagissent de la même manière mais pas toutes.

#### Comment reproduire le problème : 
- Cliquer sur `Archives` / `Enquêtes`
- Cliquer `Editer` sur `UPOI_CHB_0001_0001 | Répertoire chanté et joué au violon de Joseph Larade à Chéticamp, N-E, 1957`
-> valable aussi pour : `UPOI_ATP_0000_0009 | Répertoire chanté de Michelle Bouchereau à L'Épine, île de Noirmoutier (Vendée) en 1956`

#### Effet observé : 
- Erreur 502 Bad Gateway nginx s'affiche sur écran blanc

**Comment by lluc** [comment]
@Marion-L1 cela semble être dû au fait qu'il y a au moins 1 voix/instrument saisie avec un nombre à 0.  
Je continue à chercher ...

**Comment by lluc** [comment]
@Marion-L1  rectificatif : ce serait plutôt un bug d'affichage qui ne prends pas en compte les champs "Type de média" et "Droits d'utilisation" à *None*

**Comment by mnauge** [comment]
je viens de réussir à éditer puis sauvergarder l'enquete UPOI_CHB_0001_0001 | Répertoire chanté et joué au violon de Joseph Larade à Chéticamp, N-E, 1957en mettant à None/vide les champs "Type de média" et "Droits d'utilisation" .
