### ISSUE TITLE
ENUMERATION > Langue : Commentaire indispensable pour création de fiche

### ISSUE THREAD

**Issue by Marion-L1** [lluc/telemeta-integration#144]
A la création d'une fiche langue, un message d'erreur apparait si tous les champs munis d'une étoile rouge sont remplis. La création s'effectue lorsque la case Commentaire est remplie.

**Comment reproduire le problème :**
- `Enumération` > `Langue`
- Créer une langue
- Remplir tous les champs selon les caractère indicatifs inscrits
- Au champ `Nom` inscrire : Chiac
- Valider

**Effet observé :**
- Message d'erreur 502

**Effet attendu :**
- Création de la fiche

**Comment by mnauge** [comment]
j'ai réussi à créer la langue de "esp" sans remplir le champs facultatif _Commentaire_.

Par contre je ne sais pas bien la différence entre équivalent ISO 639-2 (bibliographie) et équivalent ISO 639-2 (terminologie) ni à quoi servent toutes les informations demandées. Si quelqu'un peu m'expliquer je suis preneur :-)
