### ISSUE TITLE
ENQUETE et ITEM > Pas d'apparition de la langue sur la page de consultation

### ISSUE THREAD

**Issue by Marion-L1** [lluc/telemeta-integration#145]
Lors de l'ajout d'une langue dans une fiche enquête ou item, celle-ci n'apparaît pas à la consultation.

**Comment reproduire le problème :*
- Editer l'item `LE COUTEAU VOLÉ Le temps que j'étais jeune enfant`
- Ajouter la langue `Chiac`
- Valider la modification

**Effet observé :**
- La langue n'apparaît pas sur la fiche modifiée

**Effet observé :** 
- Le nom de la langue apparaît

**Comment by lluc** [comment]
:thinking: la langue ne semble pas être mémorisée.

**Comment by mnauge** [comment]
Je viens de passer en mode edit sur l'item "LE COUTEAU VOLÉ Le temps que j'étais jeune enfant",
j'ai ajouté la langue Chiac puis sauvegardé. 
Et la langue reste visible en mode consultation.
ça me semble bon maintenant.
