### ISSUE TITLE
Enquête : création/modification, avec voix

### ISSUE THREAD

**Issue by lluc** [lluc/telemeta-integration#47]
Bug à création d'une enquête si voix/instrument est présent

```
KeyError at /institution/1/fond/1/mission/4/collection/add

'performance'

Request Method: 	POST
Request URL: 	http://app-francoralite-test.huma-num.fr/institution/1/fond/1/mission/4/collection/add
Django Version: 	1.8.18
Exception Type: 	KeyError
Exception Value: 	

'performance'

Exception Location: 	/srv/app/telemeta_mshs/apps/telemeta_front/views/related.py in write_relations, line 227
```

**Comment by lluc** [comment]
Le création d'enregistrments reliés *performance* ne semble pas être correctement gèré.

**Comment by Alexandre-S1** [comment]
Le problème est toujours présent. Si j'ajoute une voix/instrument à une enquête :
KeyError at /collection/edit/16


Environment:


Request Method: POST
Request URL: http://app-francoralite-test.huma-num.fr/collection/edit/16

Django Version: 1.8.18
Python Version: 2.7.15
Installed Applications:
('django.contrib.auth',
 'mozilla_django_oidc',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'suit',
 'django.contrib.admin',
 'django.contrib.staticfiles',
 'django_extensions',
 'telemeta',
 'timeside.player',
 'jsonrpc',
 'sorl.thumbnail',
 'timezones',
 'jqchat',
 'extra_views',
 'bootstrap3',
 'bootstrap_datepicker',
 'bootstrap_pagination',
 'registration',
 'rest_framework',
 'rest_framework_xml',
 'djcelery',
 'haystack',
 'djangobower',
 'django',
 'saved_searches',
 'rest_framework_swagger',
 'django_filters',
 'telemeta_mshs.apps.telemeta_api',
 'telemeta_mshs.apps.telemeta_front',
 'django_select2',
 'leaflet',
 'markdownx',
 'corsheaders')
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'telemeta_mshs.middleware.keycloak_mw.KeycloakMiddleware',
 'telemeta_mshs.middleware.session_history.SessionHistoryMiddleware')


Traceback:
File "/opt/miniconda/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/miniconda/lib/python2.7/site-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)
File "/opt/miniconda/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  89.         return handler(request, *args, **kwargs)
File "/srv/app/telemeta_mshs/apps/telemeta_front/views/collection_edit.py" in post
  56.             'collection', CollectionForm, request, *args, **kwargs)
File "/srv/app/telemeta_mshs/apps/telemeta_front/tools.py" in patch
  171.                 entity=entity
File "/srv/app/telemeta_mshs/apps/telemeta_front/tools.py" in patch_api
  212.                     headers=get_token_header(request=request))
File "/srv/app/telemeta_mshs/apps/telemeta_front/views/related.py" in write_collection_related
  117.                 str(performance["id"]) + '/musician'

Exception Type: KeyError at /collection/edit/16
Exception Value: 'id'


Environment:


Request Method: POST
Request URL: http://app-francoralite-test.huma-num.fr/collection/edit/16

Django Version: 1.8.18
Python Version: 2.7.15
Installed Applications:
('django.contrib.auth',
 'mozilla_django_oidc',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'suit',
 'django.contrib.admin',
 'django.contrib.staticfiles',
 'django_extensions',
 'telemeta',
 'timeside.player',
 'jsonrpc',
 'sorl.thumbnail',
 'timezones',
 'jqchat',
 'extra_views',
 'bootstrap3',
 'bootstrap_datepicker',
 'bootstrap_pagination',
 'registration',
 'rest_framework',
 'rest_framework_xml',
 'djcelery',
 'haystack',
 'djangobower',
 'django',
 'saved_searches',
 'rest_framework_swagger',
 'django_filters',
 'telemeta_mshs.apps.telemeta_api',
 'telemeta_mshs.apps.telemeta_front',
 'django_select2',
 'leaflet',
 'markdownx',
 'corsheaders')
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'telemeta_mshs.middleware.keycloak_mw.KeycloakMiddleware',
 'telemeta_mshs.middleware.session_history.SessionHistoryMiddleware')


Traceback:
File "/opt/miniconda/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/miniconda/lib/python2.7/site-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)
File "/opt/miniconda/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  89.         return handler(request, *args, **kwargs)
File "/srv/app/telemeta_mshs/apps/telemeta_front/views/collection_edit.py" in post
  56.             'collection', CollectionForm, request, *args, **kwargs)
File "/srv/app/telemeta_mshs/apps/telemeta_front/tools.py" in patch
  171.                 entity=entity
File "/srv/app/telemeta_mshs/apps/telemeta_front/tools.py" in patch_api
  212.                     headers=get_token_header(request=request))
File "/srv/app/telemeta_mshs/apps/telemeta_front/views/related.py" in write_collection_related
  117.                 str(performance["id"]) + '/musician'

Exception Type: KeyError at /collection/edit/16
Exception Value: 'id'
