### ISSUE TITLE
Renvoi vers l'écran d'origine, après la saisie d'une entité.

### ISSUE THREAD

**Issue by lluc** [lluc/telemeta-integration#48]
> Après avoir créé une mission, on est renvoyé vers la liste de toutes les missions. Il serait mieux d’être renvoyé vers la liste des missions du Fonds auquel la mission créée est rattachée. [Fonctionnement similaire pour tous les niveaux].

**Comment by lluc** [comment]
En utilisant un *middleware* avec mémorisation des *HTTP_REFERRER* dans une session, ça devrait être possible.

**Comment by Alexandre-S1** [comment]
- Ok pour niveau ENQUÊTE
- Ok pour niveau ITEM
**- Non vérifiable pour niveau MISSION : impossible de créer une mission (bouton Valider ne fonctionne pas)**
