### ISSUE TITLE
Fonds : modification

### ISSUE THREAD

**Issue by lluc** [lluc/telemeta-integration#49]
- lieu de conservation original : ne doit pas être obligatoire > maquette fonds 
- description : doit être obligatoire > maquette fonds
- 2 boutons identiques s'affichent en bas : "+ Ajouter une référence Nakala"
- prévoir de ne pas avoir à supprimer le pavé "Médias associés" pour valider la saisie [faire comme pour Mission]

**Comment by Alexandre-S1** [comment]
• 2 boutons identiques s'affichent en bas : "+ Ajouter une référence Nakala"
• prévoir de ne pas avoir à supprimer le pavé "Médias associés" pour valider la saisie [faire comme pour Mission]
> OK

• lieu de conservation original : ne doit pas être obligatoire > maquette fonds
• description : doit être obligatoire > maquette fonds
> Semble ok mais impossible de vérifier car bouton **Valider** ne fonctionne pas
