### ISSUE TITLE
Mission : champ description obligatoire

### ISSUE THREAD

**Issue by lluc** [lluc/telemeta-integration#50]
- description : doit être obligatoire > maquette mission

**Comment by Alexandre-S1** [comment]
Ça semble ok mais impossible de vérifier car le bouton Valider ne fonctionne pas.

**Comment by Alexandre-S1** [comment]
Ok il est bien rendu obligatoire.
Serait-il possible de notifier l'utilisateur que ce champ doit obligatoirement être rempli ? (dans le cas où l'utilisateur tente de valider sans succès parce que ce champ est vide)
