### ISSUE TITLE
Item : onglet Marqueurs

### ISSUE THREAD

**Issue by lluc** [lluc/telemeta-integration#54]
En consultation, l’onglet marqueur est vide, même lorsque des marqueurs sont ajoutés. Cet onglet semble inutile puisque les onglets apparaissent sous le player dans l’onglet Général.

**Comment by lluc** [comment]
Le _player Timeside_ est disposé au-dessus des onglets, car lorsqu'il est présent sur un onglet non affiché à l'ouverture de la page, cela provoque des dysfoncionnments.  :-(  
Au final, les marqueurs ont don été conservés sur le propre onglet.  
A voir quelle ergonomie on peut mettre en oeuvre par la suite.

**Comment by Alexandre-S1** [comment]
Ok l'onglet marqueur a été supprimé, mais le Player ne charge plus.
