### ISSUE TITLE
Pavé Voix/instrument : problème de liste déroulante "nature émission vocale"

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#57]
Lorsqu'on sélectionne un élément de la  liste déroulante "nature émission vocale", il n'est plus possible de remettre le champs à vide.

**Comment by lluc** [comment]
@Alexandre-S1 OK, donc le champ *Nature émission vocale* n'est pas obligatoire.

**Comment by Alexandre-S1** [comment]
Non, cf [https://docs.google.com/spreadsheets/d/12WJ34IB0R36tCgK3KRUSS3ayKzPAPm0BA0FD6jD6a_Q/edit#gid=928586279](url)

**Comment by lluc** [comment]
OK.

**Comment by Alexandre-S1** [comment]
Problème toujours d'actualité : Lorsqu'on sélectionne un élément de la liste déroulante "nature émission vocale", il n'est plus possible de remettre le champs à vide.

**Comment by lluc** [comment]
Il faut conserver la possiblité de corriger en cas d'erreur de manipulation => pouvoir mettre à nouveau cette saisie de liste à vide.

**Comment by mnauge** [comment]
Le problème est toujours là...

**Comment by lluc** [comment]
Non, en fait, c'est bon pour la partie "Enquête" (Collection)
