### ISSUE TITLE
Création Enquête (remplissage partiel) -> "Reset" de la page

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#60]
Je tente de créer une enquête, mais après clic sur "Valider", tous les champs se vident > équivalent d'un reset.

Ex :
https://app-francoralite-test.huma-num.fr/institution/1/fond/4/mission/7/collection/add

**Comment by lluc** [comment]
@Alexandre-S1  Hum, ce doit certaiment être dû à une erreur de saisie que je ne gère pas bien.  
Peux-tu m'indiquer les données saisies pour cette création afin que je reproduise le phénomène sur ma machine de développement ?

**Comment by Alexandre-S1** [comment]
Je viens d'arriver à créer une enquête. On dirait que c'est un problème de champs obligatoires non remplis et non notifiés. Au lieu de demander le remplissage, tout se vide. (Sauf "date" et "cote" qui sont demandés lorsque non remplis)

**Comment by lluc** [comment]
@Alexandre-S1 Oui c'est ce qui me semblait, d'où ma question ;-)

**Comment by Alexandre-S1** [comment]
titre = TEST 12-12
dates = 01/12/2019 au 02/12/2019
cote = UPOI_TES_0000_2222

**Comment by lluc** [comment]
@Alexandre-S1 OK.
Les champs suivants sont indiqués comme obligatoires dans le formulaire :  
-  contexte d'enregistrement
-  type de média
- droits d'utilisation
Je pense que c'est de là que vient l'erreur ( ils ne sont pas mis comme obligatoires dans la maquette).  
Je vais corriger ça.

**Comment by Alexandre-S1** [comment]
(Pourquoi dans ce cas n'est-il pas notifié de remplir les champs obligatoires, plutôt que de tout effacer ?)
Ok.

**Comment by lluc** [comment]
Le programme revient sur le formulaire de création alors qu'il devrait afficher le formulaire de **création en cours avec les erreurs**.  
Il faut que je regarde dans le détail.
