### ISSUE TITLE
Création Enquête (Remplissage complet) -> AttributeError

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#61]
Tous champs remplis à la création d'une enquête https://app-francoralite-test.huma-num.fr/institution/1/fond/4/mission/7/collection/add

> L'enquête est malgré tout créée même si rien ne l'indique.

**Comment by Alexandre-S1** [comment]
Je note ça ici mais ce n'est peut-être pas le lieu :
J'ai pu créer 2 enquêtes avec la même cote et le même nom : n'est-ce pas potentiellement problématique que ce soit possible ?

https://app-francoralite-test.huma-num.fr/collection/21

https://app-francoralite-test.huma-num.fr/collection/22

**Comment by lluc** [comment]
@Alexandre-S1  OK, je viens de localiser l'erreur :   
https://github.com/lluc/telemeta-integration/blob/bd6f942e1e65024ea8e0bab63be828d03fb7ec40/telemeta_mshs/apps/telemeta_front/tools.py#L108  
C'est lié au mécanisme qui permet de revenir à la page précédant un ajout de fiche (*referer*).
