### ISSUE TITLE
Item - Genre/Domaine ne fonctionne pas

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#64]

**Comment by lluc** [comment]
@Alexandre-S1  merci de me fournir quelques précisions sur le dysfonctionnement.  :-)

**Comment by Alexandre-S1** [comment]
Par exemple si je coche le genre "chanson", la modification n'est pas enregistrée. En création ni en édition.


Le 13 déc. 2019 à 15:29, lluc <notifications@github.com<mailto:notifications@github.com>> a écrit :


@Alexandre-S1<https://github.com/Alexandre-S1> merci de me fournir quelques précisions sur le dysfonctionnement. :-)

**Comment by lluc** [comment]
@Alexandre-S1  OK.
