### ISSUE TITLE
Mélodie (transcription alphabétique) : ne pas faire apparaître "None"

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#65]
Masquer si vide

**Comment by Alexandre-S1** [comment]
Non, "**_None_**" apparaît toujours.

• _**Masquer si vide**_ fonctionne si l'on fait attention d'effacer "None"

**Comment by Alexandre-S1** [comment]
Toujours d'actualité :
• Masquer si vide fonctionne si l'on fait attention d'effacer "None" (donc il est doublement intéressant de faire disparaître ce "None" par défaut.)

**Comment by lluc** [comment]
OK.
Dès que cette session de test est terminée, je déplace cette issue vers le nouveau tableau :   
https://github.com/lluc/telemeta-integration/projects/2

**Comment by mnauge** [comment]
Pour moi le problème persiste.

**Comment by mnauge** [comment]
Ok
