### ISSUE TITLE
Item Création/Edition - Le lieu de l'enquête n'apparaît pas

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#68]

**Comment by Alexandre-S1** [comment]
Problème toujours existant : en création/édition d'un item, le champ "Lieu" (qui correspond à celui de l'enquête) est vide.

**Comment by mnauge** [comment]
ok, vérifié à partir de l'enquete Enquête : UPOI_AFE_0000_0001
