### ISSUE TITLE
item ( et autres) : saut de ligne en Markdown

### ISSUE THREAD

**Issue by lluc** [lluc/telemeta-integration#71]
Les sauts de ligne (ou retour à la ligne) ne sont pas mémorisés lorsqu'ils sont saisis depuis un champ texte de type *Markdown*.

**Comment by Alexandre-S1** [comment]
Ok ils sont mémorisés.
Mais le saut de ligne ou d'autres fonctionnalités comme le tableau ne s'affichent pas en consultation : c'est le code markdown qui apparaît.
