### ISSUE TITLE
MISSION > Bug Modification du Titre

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#74]
Modification du titre + validation = AttributeError at /mission/edit/4

[AttributeError at :mission:edit:4-2.pdf](https://github.com/lluc/telemeta-integration/files/3992756/AttributeError.at.mission.edit.4-2.pdf)

**Comment by lluc** [comment]
@Alexandre-S1 non reproductible en local. Cela a peut-être été corrigé avec les modifications récentes ...
