### ISSUE TITLE
VOIX/INSTRU : Problème avec informateurs

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#81]
Consultation / Edition-modification
Lorsqu'on ajoute plusieurs voix/instruments, les informateurs sont regroupés dans le champs informateur du dernier pavé. Les champs informateurs des pavés précédents sont vidés.

[+ Côté mise en page en consultation, c'est bizarre]

Voir deux PJ.

![Voix Instru](https://user-images.githubusercontent.com/58727595/71326021-7e228380-24f5-11ea-9b13-2bdca780da54.jpeg)
![Voix Instru 2](https://user-images.githubusercontent.com/58727595/71326022-811d7400-24f5-11ea-900b-f38b2ceab20a.jpeg)

**Comment by Alexandre-S1** [comment]
Le bug est résolu, reste le problème de la lisibilité en consultation. Voir par exemple https://app.preprod.francoralite.net/collection/24

**Comment by lluc** [comment]
OK, j'ouvre une nouvelle *issue* concernant ce soucis
