### ISSUE TITLE
[collection] affichage voix/instruments

### ISSUE THREAD

**Issue by lluc** [lluc/telemeta-integration#82]
Problème en consultation : les voix/instruments se décalent "en marche d'escalier"

![francoralite_issue82](https://user-images.githubusercontent.com/1433590/74742007-25096e80-525e-11ea-8160-3eb6040c3376.png)

**Comment by lluc** [comment]
A vérifier. Cela semble fonctionner sur la version de développement ( Enquêtes )

**Comment by lluc** [comment]
Vérifier si cela est occasionné par un *centrage* involontaire de chaque ligne.

**Comment by lluc** [comment]
Problème dû à la gestion des *flex* dans le template *collection-detail.html*.  
A voir entre @lluc et @Laurence-Girault .

**Comment by lluc** [comment]
@Laurence-Girault c'est presque ça.  ;-)  
![Capture d’écran de 2020-04-06 14-27-38](https://user-images.githubusercontent.com/1433590/78558583-247b6600-7813-11ea-9a05-d08103a72806.png)
Enore un tout petit soucis sur l'alignement de colonne (*si Flex peut le gérer ...*)

**Comment by mnauge** [comment]
Pour vérifier j’essaie d'ajouter des voix/instrument dans Item : UPOI_AFE_0000_0015_001 - La destinée la rose au bois [LAF] mais après le clic sur valider, ça me ramène en mode consultation. Et mon instrument n'a pas été ajouté :-\

**Comment by lluc** [comment]
Non, c'est correct pour partie "Enquête" (collection)
