### ISSUE TITLE
Personnes : onglet déroulant, uniformiser l'orthographe

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#84]
Personnes : 
dans l'onglet déroulant, uniformiser l'orthographe, tout mettre au pluriel, y compris :
- AUTEURS
- COMPOSITEURS
- EDITEURS

**Comment by mnauge** [comment]
Ok, c'est bon. 

> ça va, ça n'a pas du être trop dur ^^
