### ISSUE TITLE
ENUMERATIONS : Corriger "Utilité" qui devrait être "FONCTION"

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#85]

**Comment by Alexandre-S1** [comment]
Corriger partout, notamment dans : 
- menu déroulant
- titre rouge en haut de page qui liste toutes les fonctions
- titre rouge en haut de page d'une fonction particulière
- titre rouge en haut de page en édition : "Utilité - Modification"
- bouton + créer une utilité

**Comment by mnauge** [comment]
ça c'est tout bon.
