### ISSUE TITLE
MISSION : consultation : date "Jusqu'à" et "Depuis"

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#88]
MISSION : 
- En consultation :  dans la date "Jusqu'à", c'est la date "Depuis" qui est reportée.

**Comment by lluc** [comment]
Ce problème est présent lorsqu'il n'y a qu'une seule enquête dans une mission.

**Comment by mnauge** [comment]
ok, vérifié sur Mission : UPOI_AFE_0000
