### ISSUE TITLE
Titres en rouge : mettre au singulier

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#89]
En consultation d'une institution / mission / d'une enquête / d'un item en particulier : enlever le s pluriel au titre en rouge en haut.
Pour :
- Institution-s
- Mission-s
- Enquête-s
- Item-s

Par exemple : https://app.preprod.francoralite.net/collection/1

**Comment by mnauge** [comment]
C'est bon aussi.

> Alexandre a clairement l'oeil, je n'aurais jamais remarqué ça ! Merci à lui.
