### ISSUE TITLE
ENQUETE création/édition - place de la zone de texte de Documentation associée

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#91]
ENQUETE :
- En création/édition, ramener à la ligne la zone de texte sous le titre Documentation associée

**Comment by mnauge** [comment]
OK !

> Juste pour info, je viens de repérer que l'url est "collection" et non enquete. 
> Ce n'est pas important et peut être entrainer une suite de nouveau bug en cascade si tu changes ça..?! Donc mieux vaut ne pas y toucher dans notre phase actuelle!  Mais je l'ai vu, c'est tout ;-)

**Comment by lluc** [comment]
@mnauge c'est "hérité" de la dénomination anglophone des tables de la base de données précédente. Il se trouve donc que la dénomination française est différente. ;-)
