### ISSUE TITLE
ENQUETE Pavé voix/instrument : supprimer le "Nombre 1"

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#92]
ENQUETE :
- Pavé voix/instrument : comme par défaut, le champ nombre est rempli avec le chiffre 1, il en résulte qu'en consultation, apparaît un "Nombre 1" même s'il n'y a pas de voix/instrument

**Comment by lluc** [comment]
@Alexandre-S1 il est possible d'abaisser la valeur du compteur à 0.

**Comment by Alexandre-S1** [comment]
Serait-il donc possible que cette valeur soit à 0 par défaut ?
Ainsi cela éviterait une manipulation et des erreurs dues à des oublis.



Le 3 mars 2020 à 11:42, lluc <notifications@github.com<mailto:notifications@github.com>> a écrit :


@Alexandre-S1<https://github.com/Alexandre-S1> il est possible d'abaisser la valeur du compteur à 0.

**Comment by lluc** [comment]
OK, je met la valeur à 0

**Comment by Alexandre-S1** [comment]
merci !

Le 5 mars 2020 à 15:17, lluc <notifications@github.com<mailto:notifications@github.com>> a écrit :


OK, je met la valeur à 0

**Comment by mnauge** [comment]
ok.
