### ISSUE TITLE
ITEM - Consultation - Fiches Coirault - manque un espace

### ISSUE THREAD

**Issue by Alexandre-S1** [lluc/telemeta-integration#96]
ITEM - Consultation
- Fiches Classification Coirault : il manque un espace après les deux points de "Classification Coirault :" (par exemple https://app.preprod.francoralite.net/coirault/1641)

**Comment by mnauge** [comment]
Comment peut on consulter toutes les références coiraults dispos  ?

**Comment by mnauge** [comment]
Il faut consulter le référentiel via opentheso :
Répertoire des chansons françaises de tradition orale(th119)
https://opentheso.huma-num.fr/opentheso/?idc=collection_1&idt=80

Attention : dans la version importé en BDD les liens URI ne sont pas bon (réréference à de vieilles adresses: http://sha.univ-poitiers.fr/musicologie/vocabulaires/coirault/).

Il faudra probablement un jour mettre ça à jour, mais il ne faut pas se précipiter car opentheso passe en version 2, donc probablement avec des changements d'URI à venir. Je pensequ'il faudra aussi envisager de mettre le referentiel Systeme_Hornbostel-Sachs en version opentheso.
